apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-crashloopbackoff-pods
  namespace: {{ $.Release.Namespace }}
  labels: 
    appname: oneuptime
spec:
  schedule: "*/2 * * * *" # At every 2nd minute.
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cleanup
            image: bitnami/kubectl:latest
            env:
            - name: namespace
              value: {{ $.Release.Namespace }}
            command:
            - /bin/bash
            - -c
            - |
                for pod in $(kubectl get pods -n $namespace --field-selector=status.phase==Failed -o jsonpath="{.items[*].metadata.name}")
                do
                    if kubectl describe pod $pod -n $namespace | grep -q 'CrashLoopBackOff'
                    then
                    kubectl delete pod $pod -n $namespace
                    fi
                done
              
          restartPolicy: OnFailure
