apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" $.Release.Name "secrets"  }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  ## Secrets Change when the release is upgraded
  ## https://github.com/helm/helm-www/issues/1259
  ## This is a workaround to keep the secrets unchanged
  {{- if .Release.IsUpgrade }}

  internal-smtp: {{ index (lookup "v1" "Secret" $.Release.Namespace (printf "%s-secrets" $.Release.Name)).data "internal-smtp" }}
  oneuptime-secret: {{ index (lookup "v1" "Secret" $.Release.Namespace (printf "%s-secrets" $.Release.Name)).data "oneuptime-secret" }}
  encryption-secret: {{ index (lookup "v1" "Secret" $.Release.Namespace (printf "%s-secrets" $.Release.Name)).data "encryption-secret" }}

  {{- range $key, $val := $.Values.probes }}
  {{- if (index (lookup "v1" "Secret" $.Release.Namespace (printf "%s-secrets" $.Release.Name)).data (printf "probe-%s" $key)) }}
  {{printf "probe-%s" $key}}: {{ (index (lookup "v1" "Secret" $.Release.Namespace (printf "%s-secrets" $.Release.Name)).data (printf "probe-%s" $key)) }}
  {{ else }}
  {{printf "probe-%s" $key}}: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- end }}

  {{ else }} # install operation

  internal-smtp: {{ randAlphaNum 32 | b64enc | quote }}
  oneuptime-secret: {{ randAlphaNum 32 | b64enc | quote }}
  encryption-secret: {{ randAlphaNum 32 | b64enc | quote }}


  {{- range $key, $val := $.Values.probes }}
  {{printf "probe-%s" $key}}: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}

  {{ end }}
  
  