services:
  llama: 
    extends:
        file: ./docker-compose.base.yml
        service: llama
    ports:
        - '8547:8547'
    build:
        network: host
        context: .
        dockerfile: ./Llama/Dockerfile