services:
  llm: 
    extends:
        file: ./docker-compose.base.yml
        service: llm
    ports:
        - '8547:8547'
    build:
        network: host
        context: .
        dockerfile: ./LLM/Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  oneuptime:
    driver: bridge