extensions:
  headers_setter:
    headers:
      - action: upsert
        key: x-oneuptime-token
        from_context: x-oneuptime-token

processors:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        include_metadata: true
      http:
        endpoint: 0.0.0.0:4318
        include_metadata: true
        cors:
          allowed_origins: ["*"]
          allowed_headers: ["*"]



exporters:
  otlphttp:
    endpoint: "http://${env:SERVER_OPEN_TELEMETRY_INGEST_HOSTNAME}:${env:OPEN_TELEMETRY_INGEST_PORT}/otlp"
    headers: {"Content-Type": "application/json"}
    auth:
      authenticator: headers_setter

service:
  telemetry:
    logs:
      level: "debug"
  extensions: [ headers_setter ]
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp]