service:
  flush: 1
  log_level: info

pipeline:
  inputs:
    - name: http
      listen: 0.0.0.0
      port: 8889

  outputs:
    - name: stdout
      match: '*'
    - name: opentelemetry
      match: '*'
      host: 'otel-collector'
      port: 4318
      header: 
        - x-oneuptime-token aaa670e0-ac15-11ef-9e8b-0bf23dab1c65
        - x-oneuptime-service-name fluent-bit


