name: MCP Server Verification

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - develop
  workflow_dispatch: # Allow manual trigger

jobs:
  verify-mcp-server:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{ github.run_number }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'

      - name: Install Common dependencies
        run: cd Common && npm install

      - name: Verify MCP server directory
        run: |
          MCP_DIR="./MCP"
          
          # Check if MCP server directory exists
          if [ ! -d "$MCP_DIR" ]; then
            echo "❌ MCP server directory not found"
            exit 1
          fi
          echo "✅ MCP server directory found: $MCP_DIR"
          
          # Count source files
          TS_FILES=$(find "$MCP_DIR" -name "*.ts" | wc -l)
          echo "📊 TypeScript source files: $TS_FILES"
          
          if [ "$TS_FILES" -eq 0 ]; then
            echo "❌ No TypeScript files found"
            exit 1
          fi
          
          # Check for essential files
          if [ -f "$MCP_DIR/package.json" ]; then
            echo "✅ Package.json file exists"
          else
            echo "❌ Package.json file missing"
            exit 1
          fi
          
          if [ -f "$MCP_DIR/README.md" ]; then
            echo "✅ Documentation exists"
          fi
          
          if [ -f "$MCP_DIR/Index.ts" ]; then
            echo "✅ Main entry point exists"
          else
            echo "❌ Main entry point missing"
            exit 1
          fi
          
          if [ -f "$MCP_DIR/Dockerfile.tpl" ]; then
            echo "✅ Dockerfile template exists"
          else
            echo "❌ Dockerfile template missing"
            exit 1
          fi
          
          # Show directory structure for debugging
          echo "📁 MCP server directory structure:"
          ls -la "$MCP_DIR" || true

      - name: Test MCP server build
        run: |
          MCP_DIR="./MCP"
          if [ -d "$MCP_DIR" ] && [ -f "$MCP_DIR/package.json" ]; then
            cd "$MCP_DIR"
            echo "🔨 Installing dependencies..."
            npm install
            echo "🔨 Testing TypeScript build..."
            npm run build
            echo "✅ MCP server build successful"
            
            # Show build output
            echo "📦 Build output:"
            ls -la build/ || true
            
            echo "🧪 Running tests..."
            npm test || echo "⚠️ No tests found or tests failed"
          else
            echo "❌ Cannot test build - missing package.json or MCP server directory"
            exit 1
          fi

      - name: Upload MCP server as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mcp-server-build
          path: ./MCP/
          retention-days: 30
