name: E2E Tests

on:
  pull_request: 
  push:
    branches-ignore:
      - 'hotfix-*'   # excludes hotfix branches
      - 'release'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{github.run_number}}
    steps:
      # Docker compose needs a lot of space to build images, so we need to free up some space first in the GitHub Actions runner
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.3.0
      - run: npm run dev
      - run: |
          # Check /status/live to see if the server is up. If the server is not up then wait for 30 seconds and try again. Keep trying for 30 minutes.
          for i in {1..60}; do
            if curl -s http://localhost/status/live; then
              break
            fi
            sleep 30
          done
      - name: Run E2E Tests. Run docker container e2e in docker compose file
        run: docker-compose -f docker-compose.dev.yml up --exit-code-from e2e --abort-on-container-exit e2e || docker-compose -f docker-compose.dev.yml logs e2e && exit 1
      
  
