name: Common Test

on:
  pull_request: 
  push:
    branches-ignore:
      - 'hotfix-*'   # excludes hotfix branches
      - 'release'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI_PIPELINE_ID: ${{github.run_number}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.3.0 
      - run: cd Common && npm install
      - run: cd Common && bash test-setup.sh
      - run: export $(grep -v '^#' config.env | xargs) && cd Common && rm -rf build && npm run test
  